### ISSUE TITLE
FEATURE - Search

### ISSUE THREAD

**Issue by brunoruas2** [FernandoCelmer/mkdocs-simple-blog#22]
I followed the mkdocs manual for deploying a search feature through plugins: search, but the theme ignored that part.

I did some tests and managed to implement a rudimentary search.

![image](https://user-images.githubusercontent.com/16859514/222283774-c4d02311-aee8-4b05-a81f-5e1e10af51f9.png)

If I focus on bringing this feature to the theme, can I count on your help with some questions?

**Comment by FernandoCelmer** [comment]
> I followed the mkdocs manual for deploying a search feature through plugins: search, but the theme ignored that part.
> 
> I did some tests and managed to implement a rudimentary search.
> 
> ![image](https://user-images.githubusercontent.com/16859514/222283774-c4d02311-aee8-4b05-a81f-5e1e10af51f9.png)
> 
> If I focus on bringing this feature to the theme, can I count on your help with some questions?

---

Yes No problems. You can ask any questions about the package.

This search feature is one of the missing features in the theme, it would be really cool to implement it, it's even on my list hahaha.

One of the templates I followed to build the theme was this repository: https://github.com/mkdocs/mkdocs-basic-theme

**Comment by FernandoCelmer** [comment]
Hey @brunoruas2, the new search feature has been created! 

A new version of the package was generated from your request for deployment. The latest version is [0.0.8](https://github.com/FernandoCelmer/mkdocs-simple-blog/releases/tag/v0.0.8), you can download it from [PyPi]( https://pypi.org/project/mkdocs-simple-blog/) or using the terminal command `pip install -U mkdocs-simple-blog`. 

- https://github.com/FernandoCelmer/mkdocs-simple-blog/pull/24

Thanks! :+1:

**Comment by brunoruas2** [comment]
Congratulations!

Unfortunately I can't help on this feature because I don't found any free time in this period.

Best regards.
