### ISSUE TITLE
<code> indentation error

### ISSUE THREAD

**Issue by eeev** [FernandoCelmer/mkdocs-simple-blog#26]
Hello all,

I found a small design issue with the `<code>` blocks in this theme (you can also see it on the current preview image).

**The code indentation on multi-line code blocks currently has a slight error**:
- For single-line blocks, using single backticks, applying a padding is fine, as is done in `theme.css`
- For multi-line blocks, using triple backticks, since the very same padding as above is applied, this will break correct indentation; Multi-line blocks only use a single `<code>` block inside a `<pre>` block, especially for multi-line code

In the preview image, you can see that the `mkdocs.yml`-line is indented not by the code itself, but by the padding applied to the `<code>` block surrounding it. However, this padding does not translate over to the other \n's, hence the `docs/`-line beneath is not aligned.

My current fix is simply to override the css:

```
pre code {
    padding: 0;
}
```

For each `<code>` block nested inside a `<pre>` block, as is the case in multi-line blocks, the padding is reset. Alternatively, you may still add vertical padding, as it does not impact the indentation. In my personal blog, I have added this rule, and it seems to be fixing the issue.

Thank you for your time, please let me know what you think about this.

**Comment by FernandoCelmer** [comment]
@eeev 
![Alt Text](https://media.giphy.com/media/xULW8v7LtZrgcaGvC0/giphy.gif)
